name: "Setup Node.js and yarn"
description: "Sets up Node.js and yarn with caching"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        registry-url: 'https://registry.npmjs.org'

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Setup cache
      uses: actions/cache@v4
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/.yarnrc.yml') }}
        restore-keys: |
          ${{ runner.os }}-yarn-